# Generated by Django 3.1.3 on 2020-11-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_person_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent_from',
        ),
    ]
