# Generated by Django 3.1.3 on 2020-11-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201126_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.TextField(default=''),
        ),
    ]
