# Generated by Django 3.1.3 on 2020-12-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_person_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
